DROP DATABASE IF EXISTS test;
CREATE DATABASE test;
use test;


DROP DATABASE IF EXISTS fuga;
CREATE TABLE fuga (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name TEXT NOT NULL
)DEFAULT CHARACTER SET=utf8;
